services:
  postgres:
    image: postgres:latest
    container_name: gpt-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gpt-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678